<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Personnel extends Model
{
    //
    protected $guarded = ['id'];

    public function user(){
        return $this->hasOne(User::class,'personnel_id');
    }


    public function matieres(){
        return $this->belongsToMany('App\Matiere','enseignes','personnel_id','matiere_id');
    }

    public function classes(){
        return $this->belongsToMany('App\Classe','interventions','personnel_id','classe_id');
    }

    public function interventions(){
        return $this->hasMany('App\Intervention');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function($per){
            User::create([
                'name'=>$per->nom_complet,
                'email'=>strtolower($per->nom).$per->id."@sigma.com",
                'password'=>bcrypt("12345678"),
                'personnel_id'=>$per->id,
                'role_id'=>10,
            ]);

        });

        self::deleted(function($delper){
            $user= User::where("personnel_id",$delper->id)->first();
            User::destroy($user->id);


        });



        }

    //add by ken
    public function salle(){
        return $this->belongsTo('App\Salle');
    }

    public function cours(){
        return $this->hasMany('App\Cours');
    }
    }

